const clientWorkspaceData = [
    {
        "id": "asset-160508-3226",
        "date": "2026-05-26",
        "type": "TEXT",
        "title": {
            "en": "Morning Brief",
            "zh": "中文剧本"
        },
        "displayTitle": {
            "en": "Morning Brief",
            "zh": "中文剧本"
        },
        "description": {
            "en": "Dispatched from central operations terminal.",
            "zh": "自中央控制台分发交付。"
        },
        "videoUrl": "",
        "imageUrl": "",
        "downloadUrl": "https://docs.google.com/document/d/1DJr3ba_0QsZzMznmXlOswqCpP_Vjcvwl4wtcXTNHnl8/edit?tab=t.0",
        "downloadLabel": "// View Manifest",
        "copyBoxTitle": {
            "en": "Clean Text Output",
            "zh": "净值内容输出"
        },
        "copyBoxContent": {
            "en": "Flash Analysis: Top 5 Global Developments\n1. The IMF Formalizes \"Agentic Payment\" Frameworks\nNews: IMF Note No. 2026/004: How Agentic AI Will Reshape Payments\nPillar: V (Agentic Property Rights & NHI)\nThe Tokenized Wave: We are moving from \"Human-in-the-loop\" to \"Human-on-the-loop.\" Value is no longer just signed by biological entities; it is being autonomously negotiated and settled by non-human identities (NHIs).\nThe Austrian Ground: Menger’s Law of Diminishing Marginal Utility. As the cost of a \"transaction action\" drops toward zero via agents, the marginal utility of a single human signature collapses, necessitating a new unit of trust.\nThe Prediction: The \"Liability Wall\" will not be solved by law, but by Professional Indemnity Insurance for Agents, creating a new trillion-dollar sub-sector of the DeFi insurance market.\n2. DePIN Pivot: Transition from \"Narrative\" to \"Hardware Uptime\"\nNews: DEXTools: The 2026 DePIN Revolution\nPillar: IV (Tokenized Infrastructure & Compute)\nThe Tokenized Wave: Capital is rotating out of \"AI-wrapper\" tokens into verifiable hardware infrastructure. Tokens are being re-priced based on compute-yield rather than speculative hype.\nThe Austrian Ground: Lachmannian Capital Heterogeneity. Compute is not a homogenous blob; the market is finally distinguishing between \"high-grade\" low-latency nodes and \"malinvested\" consumer-grade clusters.\nThe Prediction: Mainstream analysts think this is a \"crypto crash,\" but it is actually the first Austrian Capital Re-adjustment of the AI era—flushing out unproductive speculative assets.\n3. The Identity Battleground: Agents as \"Insider Threats\"\nNews: Cybersecurity 2026: Agentic AI and the Human Factor\nPillar: VI (Institutional & Legal Frameworks)\nThe Tokenized Wave: Trust signals are being erased. Identity is no longer a \"fact\" but a Trust Score generated by continuous agentic behavior analysis.\nThe Austrian Ground: The Calculation Problem. Centralized security cannot \"calculate\" trust fast enough. Only decentralized, reputation-weighted systems can manage the information overflow of agentic loops.\nThe Prediction: Identity will cease to be a \"state-issued\" document and will become a dynamically priced tokenized asset based on historical uptime and liability coverage.\n4. Jevons Paradox in AI Efficiency: The \"Always-On\" Infrastructure\nNews: Brookfield: Building the Backbone of AI at Scale\nPillar: IV (Tokenized Infrastructure & Compute)\nThe Tokenized Wave: As inference efficiency increases, total energy consumption is rising, not falling. This creates a permanent floor for the value of \"Energy-Backed Tokens.\"\nThe Austrian Ground: The Jevons Paradox. Increased efficiency in token generation is lowering the \"price\" of agentic labor, which is exploding the total quantity demanded.\nThe Prediction: We are entering a \"Tokenized Energy Standard\" where the volatility of AI agents is directly pegged to the stability of regional energy grids.\n5. EU AI Act vs. Browser-Based Open Source\nNews: 4 Agentic AI Trends in 2026\nPillar: VI (Institutional & Legal Frameworks)\nThe Tokenized Wave: Regulation is targeting large models, but the \"Wave\" is moving toward browser-based, lightweight, open-source agents that bypass traditional jurisdictional oversight.\nThe Austrian Ground: Spontaneous Order. Regulation is a \"top-down\" attempt to freeze a \"bottom-up\" evolution. The market is routing around the EU AI Act via localized execution.\nThe Prediction: Large \"Sovereign AI\" models will become the new \"Postal Service\"—reliable but slow—while the real economic value moves to the \"Shadow Agent\" economy.",
            "zh": "\n开头 (0-10s)\n[镜头快切，霓虹转场，手持手机]\n“IMF（国际货币基金组织）刚刚取消了你的‘支付’键。这不是演习。2026年最新指令 004 号文件，正式将我们从‘点击支付’推向了‘决策支付’。你的 AI 不再只是个聊天机器人，它正式成为了你的首席财务官（CFO）。但，这背后的代价是什么？”\n逻辑 (10-40s)\n[分屏：AI 大脑 vs 实体金库]\n“把这想象成你银行账户的‘自动驾驶’。IMF 正在构建一套三层架构的数字宪法，连接 AI 逻辑与真实资金：\n第一层（意图层）： AI 负责‘思考’并发现商机；\n第二层（控制层）： 这是‘确定性护栏’，防止 AI 乱花钱；\n第三层（结算层）： 钱在这里真正完成转账。\n他们管这叫 KYA（了解你的代理人）。这是 2026 年版的身份核验，对象是为你干活的硅基大脑。”\n"
        }
    }
];